//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaOnlineUmes.libreria {
    
    
    public partial class a2d1m5i9n7i6s7t0r7a9do4r {
    }
}
