//------------------------------------------------------------------------------
<<<<<<< HEAD
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
=======
// <generado automáticamente>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </generado automáticamente>
>>>>>>> be2292678815b0c1a1366618db0a74549df8c958
//------------------------------------------------------------------------------

namespace LibreriaOnlineUmes.libreria {
    
    
    public partial class producto {
    }
}
